In [164]:
import pandas as pd
import numpy as np
import math

In [292]:
df = pd.read_excel('2010_mens.xlsx')

In [293]:
df.shape

(2679, 78)

In [294]:
df.tourney_date = pd.to_datetime(df.tourney_date, yearfirst=True, format='%Y%m%d')
df = df.sort_values(by='tourney_date').reset_index(drop=True)

In [261]:
df.shape

(2679, 78)

In [295]:
df

,tourney_id,tourney_name,series,court,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,...,LBW,LBL,PSW,PSL,SJW,SJL,MaxW,MaxL,AvgW,AvgL
0,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,6,104571,...,1.40,2.75,1.377,3.410,1.400,2.750,NaN,NaN,NaN,NaN
1,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,30,103285,...,2.10,1.67,2.350,1.685,2.000,1.727,NaN,NaN,NaN,NaN
2,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,16,103285,...,1.04,9.00,1.087,9.950,1.030,10.000,NaN,NaN,NaN,NaN
3,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,24,103285,...,1.12,5.50,1.159,6.390,1.125,5.500,NaN,NaN,NaN,NaN
4,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,11,103722,...,1.44,2.62,1.483,2.900,1.440,2.630,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2674,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,1,103819,...,1.13,5.50,1.140,7.100,1.130,6.000,1.14,8.20,1.11,6.39
2675,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,4,103819,...,1.44,2.63,1.420,3.180,1.360,3.000,1.50,3.24,1.40,2.92
2676,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,14,104925,...,1.36,3.00,1.480,2.920,1.440,2.750,1.48,3.15,1.40,2.88
2677,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,13,104925,...,1.25,3.75,1.250,4.600,1.250,3.750,1.30,4.76,1.24,4.03
2678,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,11,104745,...,1.83,1.83,2.090,1.850,1.900,1.900,2.11,2.00,1.92,1.84

In [296]:
data = np.ones((len(df), 1))*1500

df['winner_elo'] = data
df['loser_elo'] = data

In [171]:
sub_df = df[['winner_name', 'loser_name', 'winner_elo', 'loser_elo']]
sub_df

           winner_name           loser_name  winner_elo  loser_elo
0     Marcos Baghdatis           Mardy Fish      1500.0     1500.0
1       Radek Stepanek         Gael Monfils      1500.0     1500.0
2       Radek Stepanek         John Millman      1500.0     1500.0
3       Radek Stepanek  Alexandr Dolgopolov      1500.0     1500.0
4        Florent Serra       Julian Reister      1500.0     1500.0
...                ...                  ...         ...        ...
2674     Roger Federer         David Ferrer      1500.0     1500.0
2675     Roger Federer       Novak Djokovic      1500.0     1500.0
2676    Novak Djokovic         Andy Roddick      1500.0     1500.0
2677    Novak Djokovic        Tomas Berdych      1500.0     1500.0
2678      Rafael Nadal       Novak Djokovic      1500.0     1500.0

[2679 rows x 4 columns]

In [172]:
sub_df.isnull().sum()

winner_name    0
loser_name     0
winner_elo     0
loser_elo      0
dtype: int64

In [297]:
def probability(elo_1, elo_2):
    
    return 1/(1 + math.pow(10, (elo_1 - elo_2)/400))

In [298]:
def elo_rating(rating_player, rating_opponent, K):
    
    prob_a = probability(rating_opponent, rating_player)
    prob_b = probability(rating_player, rating_opponent)
    
    rating_player = rating_player + K * (1 - prob_a)
    rating_opponent = rating_opponent + K * (0 - prob_b)
    
    return rating_player, rating_opponent

In [205]:
sub_df.shape

(2679, 4)

In [194]:
elo_winner, elo_loser = elo_rating(sub_df.winner_elo[670], sub_df.loser_elo[670], 30)
elo_winner

1528.7080052393337

In [257]:
df.at[3, 'winner_elo'] = 1700
df.at[3, 'winner_elo']

1700.0

In [254]:
len(df[df['winner_name']=='Novak Djokovic'].iloc[43:, :].winner_elo.values.tolist())

13

In [299]:
for i in range(df.shape[0]):
    elo_winner, elo_loser = elo_rating(df.at[i, 'winner_elo'], df.at[i, 'loser_elo'], 30)
    
    df.at[i, 'winner_elo'] = elo_winner
    df.at[i, 'loser_elo'] = elo_loser
    
    winner_name = df.winner_name[i]
    loser_name = df.loser_name[i]
    
    sub_ww = df[df['winner_name']==winner_name].winner_elo.iloc[i:]
    sub_ll = df[df['loser_name']==loser_name].loser_elo.iloc[i:]
    sub_lw = df[df['loser_name']==winner_name].loser_elo.iloc[i:]
    sub_wl = df[df['winner_name']==loser_name].winner_elo.iloc[i:]
    
    sub_ww.replace(to_replace=sub_ww.values.tolist(), value=elo_winner, inplace=True)
    sub_ll.replace(to_replace=sub_ll.values.tolist(), value=elo_loser, inplace=True)
    sub_lw.replace(to_replace=sub_lw.values.tolist(), value=elo_winner, inplace=True)
    sub_wl.replace(to_replace=sub_wl.values.tolist(), value=elo_loser, inplace=True)
    
    df.update(sub_ww)
    df.update(sub_ll)
    df.update(sub_lw)
    df.update(sub_wl)

In [300]:
df

,tourney_id,tourney_name,series,court,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,...,PSW,PSL,SJW,SJL,MaxW,MaxL,AvgW,AvgL,winner_elo,loser_elo
0,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,6,104571,...,1.377,3.410,1.400,2.750,NaN,NaN,NaN,NaN,1515.000000,1485.000000
1,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,30,103285,...,2.350,1.685,2.000,1.727,NaN,NaN,NaN,NaN,1515.000000,1485.000000
2,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,16,103285,...,1.087,9.950,1.030,10.000,NaN,NaN,NaN,NaN,1529.352800,1485.647200
3,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,24,103285,...,1.159,6.390,1.125,5.500,NaN,NaN,NaN,NaN,1543.088544,1486.264256
4,2010-339,Brisbane International,ATP250,Outdoor,Hard,32,A,2010-01-03,11,103722,...,1.483,2.900,1.440,2.630,NaN,NaN,NaN,NaN,1515.000000,1485.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2674,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,1,103819,...,1.140,7.100,1.130,6.000,1.14,8.20,1.11,6.39,1529.352800,1485.647200
2675,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,4,103819,...,1.420,3.180,1.360,3.000,1.50,3.24,1.40,2.92,1529.352800,1485.647200
2676,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,14,104925,...,1.480,2.920,1.440,2.750,1.48,3.15,1.40,2.88,1515.647200,1499.352800
2677,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,13,104925,...,1.250,4.600,1.250,3.750,1.30,4.76,1.24,4.03,1514.352800,1470.647200
2678,2010-605,ATP World Tour Finals,Masters Cup,Indoor,Hard,8,F,2010-11-21,11,104745,...,2.090,1.850,1.900,1.900,2.11,2.00,1.92,1.84,1529.352800,1485.647200

In [301]:
df.winner_elo.unique()

array([1515.        , 1529.35280001, 1543.08854424, 1500.64719999,
       1556.23774139, 1515.64719999, 1528.70800524, 1514.35280001,
       1516.26425577, 1516.85080285, 1501.29199476, 1514.40728902,
       1500.        , 1515.61925815, 1500.05458207, 1501.2096737 ,
       1501.85696675, 1529.97211242, 1499.97205816, 1514.38074185,
       1529.38165205, 1500.67508757, 1530.        , 1528.68027515,
       1513.73349208, 1514.32491243, 1515.02794184, 1516.26650792,
       1529.38069207, 1514.97211242, 1502.50205642, 1513.78798929,
       1514.97205816, 1568.83074765, 1529.32747514, 1503.03319316,
       1530.61925815])

In [302]:
df.loser_elo.unique()

array([1485.        , 1485.64719999, 1486.26425577, 1484.35280001,
       1486.85080285, 1499.35280001, 1471.29199476, 1470.64719999,
       1513.08854424, 1526.23774139, 1498.70800524, 1471.85696675,
       1470.        , 1485.02794184, 1471.2096737 , 1470.05458207,
       1484.40728902, 1485.67508757, 1469.38074185, 1484.97205816,
       1472.52980372, 1484.97211242, 1500.        , 1470.67252486,
       1470.61930793, 1470.02788758, 1485.61925815, 1499.38069207,
       1486.26650792, 1470.67508757, 1498.76219935, 1471.82906649,
       1484.38074185, 1487.40699373, 1471.31972485, 1538.20454823,
       1500.02794184])

In [288]:
sub.winner_elo.iloc[3:].replace(to_replace=sub.winner_elo.iloc[3:].values.tolist(), value=2600, inplace=True)

In [290]:
sub

,tourney_name,winner_name,winner_elo,loser_elo
167,Australian Open,Novak Djokovic,1515.0,1485.0
168,Australian Open,Novak Djokovic,1515.0,1485.0
169,Australian Open,Novak Djokovic,1515.0,1485.0
170,Australian Open,Novak Djokovic,2600.0,1485.0
457,ABN AMRO World Tennis Tournament,Novak Djokovic,2600.0,1485.0
458,ABN AMRO World Tennis Tournament,Novak Djokovic,2600.0,1485.0
459,ABN AMRO World Tennis Tournament,Novak Djokovic,2600.0,1485.0
627,Dubai Tennis Championships,Novak Djokovic,2600.0,1485.0
628,Dubai Tennis Championships,Novak Djokovic,2600.0,1485.0
629,Dubai Tennis Championships,Novak Djokovic,2600.0,1485.0
630,Dubai Tennis Championships,Novak Djokovic,2600.0,1485.0
640,Dubai Tennis Championships,Novak Djokovic,2600.0,1485.0
644,BNP Paribas Open,Novak Djokovic,2600.0,1485.0
653,BNP Paribas Open,Novak Djokovic,2600.0,1485.0
922,Monte Carlo Masters,Novak Djokovic,2600.0,1485.0
923,Monte Carlo Masters,Novak Djokovic,2600.0,1485.0
924,Monte Carlo Masters,Novak Djokovic,2600.0,1485.0
996,Internazionali BNL d'Italia,Novak Djokovic,2600.0,1485.0
998,Internazionali BNL d'Italia,Novak Djokovic,2600.0,1485.0
1109,Serbia Open,Novak Djokovic,2600.0,1485.0
1230,French Open,Novak Djokovic,2600.0,1485.0
1232,French Open,Novak Djokovic,2600.0,1485.0
1259,French Open,Novak Djokovic,2600.0,1485.0
1260,French Open,Novak Djokovic,2600.0,1485.0
1399,AEGON Championships,Novak Djokovic,2600.0,1485.0
1551,Wimbledon,Novak Djokovic,2600.0,1485.0
1584,Wimbledon,Novak Djokovic,2600.0,1485.0
1585,Wimbledon,Novak Djokovic,2600.0,1485.0
1586,Wimbledon,Novak Djokovic,2600.0,1485.0
1587,Wimbledon,Novak Djokovic,2600.0,1485.0
1919,Rogers Masters,Novak Djokovic,2600.0,1485.0
1920,Rogers Masters,Novak Djokovic,2600.0,1485.0
1921,Rogers Masters,Novak Djokovic,2600.0,1485.0
1963,Western & Southern Financial Group Masters,Novak Djokovic,2600.0,1485.0
1964,Western & Southern Financial Group Masters,Novak Djokovic,2600.0,1485.0
2088,US Open,Novak Djokovic,2600.0,1485.0
2089,US Open,Novak Djokovic,2600.0,1485.0
2091,US Open,Novak Djokovic,2600.0,1485.0
2104,US Open,Novak Djokovic,2600.0,1485.0
2116,US Open,Novak Djokovic,2600.0,1485.0
2190,US Open,Novak Djokovic,2600.0,1485.0
2343,China Open,Novak Djokovic,2600.0,1485.0
2345,China Open,Novak Djokovic,2600.0,1485.0
2346,China Open,Novak Djokovic,2600.0,1485.0
2347,China Open,Novak Djokovic,2600.0,1485.0
2350,China Open,Novak Djokovic,2600.0,1485.0
2371,Shanghai Masters,Novak Djokovic,2600.0,1485.0
2407,Shanghai Masters,Novak Djokovic,2600.0,1485.0
2415,Shanghai Masters,Novak Djokovic,2600.0,1485.0
2594,Swiss Indoors,Novak Djokovic,2600.0,1485.0
2600,Swiss Indoors,Novak Djokovic,2600.0,1485.0
2601,Swiss Indoors,Novak Djokovic,2600.0,1485.0
2606,Swiss Indoors,Novak Djokovic,2600.0,1485.0
2652,BNP Paribas Masters,Novak Djokovic,2600.0,1485.0
2676,ATP World Tour Finals,Novak Djokovic,2600.0,1485.0
2677,ATP World Tour Finals,Novak Djokovic,2600.0,1485.0